name: nordic_dfu_example
description: Demonstrates how to use the nordic_dfu plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.3.1
  nordic_dfu:
    path: ../
  permission_handler: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/03.01.1.008.004.zip
